### ISSUE TITLE
Rapid addition and removal of tabs distorts tab order

### ISSUE THREAD

**Issue by MatthewHawkins** [webforj/webforj#560] opened 2024-03-26 15:02 UTC
We have functionality where a user can switch between "views". For example, we have a "Sales" and a "Purchasing" view. Every view has their own tabs on the TabbedPane. When a user switches between views, we delete all the tabs from the TabbedPane and add the tabs that are specific for that view.

Usually, this works good and without any problems. However, sometimes (we notice it when the server is really busy) the tabs are not being added in the right order.

In the following program, a button allows for just adding or removing tabs, with another button for doing both. When clicking the add and remove button rapidly **WITH** the console logs, the issue doesn't happen, but when rapidly clicking **WITHOUT**, then the tabs are out of order.

From Prodin: The demo in action: https://app.screencast.com/IeC3vy5Q0uhez.

```java

package samples;

import com.webforj.App;
import com.webforj.component.button.Button;
import com.webforj.component.html.elements.Div;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.component.tabbedpane.TabbedPane;
import com.webforj.component.window.Frame;
import com.webforj.exceptions.WebforjException;

public class RemoveTabsExampleM extends App {

  private TabbedPane pane = new TabbedPane();
  Button addAll = new Button ("Add all tabs", e -> addTabs());
  Button removeAll = new Button ("Remove all tabs", e -> pane.removeAllTabs());
  Button addAndRemove = new Button ("Remove and add all tabs", e -> addAndRemove());
  FlexLayout buttonLayout = new FlexLayout(addAll, removeAll, addAndRemove);

  @Override
  public void run() throws WebforjException {
    Frame mainFrame = new Frame();
    mainFrame.add(pane, buttonLayout);
  }

  public void addTabs(){
    for(int i = 0; i < 10; i++){
        pane.addTab("Tab " + i, new Div());
    }
  }

  public void addAndRemove(){
    // Removing the consoleLog method calls causes the behavior to match Rick's
    consoleLog("Tab num before: " + pane.getTabs().size());
    pane.removeAllTabs();
    consoleLog("Tab num after: " + pane.getTabs().size());
    this.addTabs();
  }
}
```

**Comment by hyyan** [comment] 2024-04-04 09:08
@MatthewHawkins, I'm unable to reproduce the issue you mentioned. The tabs are being added and removed correctly, both with and without the console log. Therefore, I'm closing this issue. If you have more information or can provide a step-by-step guide on how to reproduce the problem, please reopen this or create a new issue.

**Closed by hyyan** 2024-04-04 09:08 UTC
Labels: Status: Cannot Reproduce
