### ISSUE TITLE
MIME Type Error when running mvn install

### ISSUE THREAD

**Issue by Tewil** [webforj/webforj#557] opened 2024-03-22 09:35 UTC
I have an error with the 
https://github.com/webforj/webforj-hello-world
project.
evrytime i run the mvn install commmand i get the follwing error:

```
[INFO] Installing DWCJ App using URL: http://localhost:8888/webforj-install
[ERROR] Error attempting deployment: MIME type
java.lang.NullPointerException: MIME type
    at java.util.Objects.requireNonNull (Objects.java:233)
    at org.apache.hc.core5.util.Args.notNull (Args.java:169)
    at org.apache.hc.core5.util.Args.notBlank (Args.java:111)
    at org.apache.hc.core5.http.ContentType.create (ContentType.java:314)
    at org.apache.hc.core5.http.ContentType.create (ContentType.java:327)
    at com.webforj.maven.install.WebforjInstall.createMultipartEntity (WebforjInstall.java:136)
    at com.webforj.maven.install.WebforjInstall.lambda$execute$548caef2$1 (WebforjInstall.java:100)
    at io.vavr.control.Try$WithResources2.lambda$of$9d9ddcd5$1 (Try.java:1424)
    at io.vavr.control.Try.of (Try.java:75)
    at io.vavr.control.Try$WithResources2.of (Try.java:1423)
    at com.webforj.maven.install.WebforjInstall.execute (WebforjInstall.java:101)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

my system:

- BBj Version 24.00
- maven 3.9.6

the only change i made to the repo was the following in the pom.xml file:

![image](https://github.com/webforj/webforj/assets/68031256/27f48a09-9aac-4cbd-a1cb-da8d571aa764)

i cleared the .m2 folder of maven but it does not work
i do get this error after the dwcj to webforj refactoring

there have been no logs created, so i cannot inspect these

**Comment by kevinhagel** [comment] 2024-03-22 11:22
We need to see more of his project.  What is his project producing, a jar or zip file, or something else?
MIME type means he's trying to upload the wrong kind of file.
Are you having this problem, is Matthew?  We have not committed anything new to the maven install plugin since last week when we did the dwcj->webforj name changes.
I'll modify my helloworldjava project to use those repositories, see if it happens on my windows machine.

**Comment by hyyan** [comment] 2024-03-22 11:23
@kevinhagel he using the hello world sample.

**Comment by kevinhagel** [comment] 2024-03-22 11:39
Cannot reproduce on my parallels desktop windows 11.

The invalid mimetype is happening before the file is sent to BBj, there is in webforj-bbj-install-lib or BBj services involved.

Can we get more information from the user.  BBj Version 24.00 can be many different versions. is he using an install that comes with the fat jar or he he getting and older DWCJ plugins environment?

Ask the user what his terminal says when he runs it.  His statement that there are no logs is false.

```bash
[INFO] -------DWCJ Deploy to Server:-------------
[INFO] Installing DWCJ App using URL: http://localhost:8888/webforj-install
[INFO] Installing file C:\Users\kevin\webforj-hello-world\target\hello-world-java-1.0-SNAPSHOT.jar, mimetype = application/java-archive
[INFO] ----------------------------------------
```


````xml`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.webforj.samples</groupId>
  <artifactId>hello-world-java</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <webforj.version>24.00-SNAPSHOT</webforj.version>
  </properties>

  <repositories>
    <repository>
      <id>ossrh-shapshot</id>
      <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>ossrh-snapshots</id>
      <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>


  <dependencies>
    <dependency>
      <groupId>com.webforj</groupId>
      <artifactId>webforj</artifactId>
      <version>${webforj.version}</version>
      <type>pom</type>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>com.webforj</groupId>
        <artifactId>webforj-install-maven-plugin</artifactId>
        <version>${webforj.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>install</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <deployurl>http://localhost:8888/webforj-install</deployurl>
          <classname>samples.HelloWorldApp</classname>
          <publishname>hello-world</publishname>
          <debug>true</debug>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by kevinhagel** [comment] 2024-03-22 11:49
It is happening in the createMultipartEntity(File file) method.

    ContentType mimetype = ContentType.create(Files.probeContentType(file.toPath()));
    getLog().info("Installing file " + file + ", mimetype = " + mimetype);

I can put a try catch around it, just assume it is  application/java-archive if the file ends in "jar"

**Comment by Tewil** [comment] 2024-03-22 11:51
![image](https://github.com/webforj/webforj/assets/68031256/b9e7975a-9d46-4f4d-a7ee-6d7bdd87cde7)


this is my bbj version i am running on


i could not find any logs in the log file regarding webforj

**Comment by kevinhagel** [comment] 2024-03-22 12:56
You are using java 17 or later version?  it appears your system's configured File Detectors are returning a null value when the mime type of the target jar is being detected.

**Comment by Tewil** [comment] 2024-03-22 13:17
i am using java 17.0.3.1

**Closed** 2024-04-10 12:01 UTC
Labels: Type: Bug
